### ISSUE TITLE
Scene is missing a fullscreen camera error

### ISSUE THREAD

**Issue by tjiahen** [Albert/ClawVR#1]
Just tested out the latest commit. Got this error when run it in dev run mode.

b2d4c18bb4af10b3c80be0ebae398593189ebd8f

**Comment by Albert** [comment]
Hi Wizztjh --

This is actually the old library.  Sorry, I hadn't earlier updated the README here to direct to the new one.

The new version of the code has an extensive README that should help you get stood up.
